// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	publisher "perpustakaan/features/publisher"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteByID provides a mock function with given fields: publisherID
func (_m *Repository) DeleteByID(publisherID int) (int, error) {
	ret := _m.Called(publisherID)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(publisherID)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(publisherID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(publisherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: newPublisher
func (_m *Repository) Insert(newPublisher publisher.Publisher) (int, error) {
	ret := _m.Called(newPublisher)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(publisher.Publisher) (int, error)); ok {
		return rf(newPublisher)
	}
	if rf, ok := ret.Get(0).(func(publisher.Publisher) int); ok {
		r0 = rf(newPublisher)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(publisher.Publisher) error); ok {
		r1 = rf(newPublisher)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Paginate provides a mock function with given fields: page, size, searchKey
func (_m *Repository) Paginate(page int, size int, searchKey string) ([]publisher.Publisher, error) {
	ret := _m.Called(page, size, searchKey)

	var r0 []publisher.Publisher
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]publisher.Publisher, error)); ok {
		return rf(page, size, searchKey)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []publisher.Publisher); ok {
		r0 = rf(page, size, searchKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]publisher.Publisher)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(page, size, searchKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectByID provides a mock function with given fields: publisherID
func (_m *Repository) SelectByID(publisherID int) (*publisher.Publisher, error) {
	ret := _m.Called(publisherID)

	var r0 *publisher.Publisher
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*publisher.Publisher, error)); ok {
		return rf(publisherID)
	}
	if rf, ok := ret.Get(0).(func(int) *publisher.Publisher); ok {
		r0 = rf(publisherID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*publisher.Publisher)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(publisherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *Repository) Update(_a0 publisher.Publisher) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(publisher.Publisher) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(publisher.Publisher) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(publisher.Publisher) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
